--- #YAML:1.0
name:               Net-Nslookup
version:            2.00
abstract:           Provide nslookup(1)-like capabilities
author:
    - darren chamberlain <darren@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::DNS:    0
    Test::More:  0.45
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
